"""Remove uniqueness from Epic title

Revision ID: 3115b182e576
Revises: 89a908e75887
Create Date: 2025-05-31 05:22:59.066885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3115b182e576'
down_revision: Union[str, None] = '89a908e75887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('epics', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('epics_title_key'), 'epics', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('epics_title_key'), 'epics', ['title'], postgresql_nulls_not_distinct=False)
    op.alter_column('epics', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
