"""Epic and Tasks models

Revision ID: 39a0eee19515
Revises: 6c32349fd203
Create Date: 2025-05-30 21:33:23.128566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a0eee19515'
down_revision: Union[str, None] = '6c32349fd203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('owner_email', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'DONE', name='epicstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('epic_id', sa.UUID(), nullable=False),
    sa.Column('hours_estimate', sa.Integer(), nullable=False),
    sa.Column('hours_spent', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'DOING', 'DONE', name='taskstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('epics')
    # ### end Alembic commands ###
